services:
  web:
    container_name: board4you-server
    build: .
    command: ./server
    ports:
      - "80:3000"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: board4you-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "board4you"
      POSTGRES_USER: "board4you_user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /var/lib/postgresql/data
      - ./db/init/:/docker-entrypoint-initdb.d

    ports:
      - "4000:4000"
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U board4you_user -d board4you"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  adminer:
    container_name: board4you-db-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

secrets:
  db_password:
    file: ./db/credentials/password.txt