services:
  web:
    container_name: board4you-server
    # image: ghcr.io/gachilord/board4you-server:1.0.9
    build: .
    restart: always
    command: ./server 
    ulimits:
      nofile:
        soft: 30000
        hard: 100000
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: "board4you"
    ports:
      - "3000:3000"
    secrets:
      - db_password
      - jwt_secret
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /tmp/board4you/:/tmp/board4you/
  db:
    container_name: board4you-db
    image: postgres:16
    restart: always
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: "board4you"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /tmp/board4you/:/tmp/board4you/
      - ./db/postgres.conf/:/etc/postgresql/postgresql.conf
    secrets:
      - db_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U board4you -d board4you"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  adminer:
    container_name: board4you-db-adminer
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: dev@examle.com
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8080:80

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
