/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_authed_free(a: number): void;
export function __wbg_info_free(a: number): void;
export function __wbg_get_info_payload(a: number, b: number): void;
export function __wbg_set_info_payload(a: number, b: number, c: number): void;
export function __wbg_auth_free(a: number): void;
export function __wbg_pull_free(a: number): void;
export function __wbg_get_pull_current(a: number, b: number): void;
export function __wbg_set_pull_current(a: number, b: number, c: number): void;
export function __wbg_get_pull_undone(a: number, b: number): void;
export function __wbg_set_pull_undone(a: number, b: number, c: number): void;
export function __wbg_setsize_free(a: number): void;
export function __wbg_get_setsize_data(a: number): number;
export function __wbg_set_setsize_data(a: number, b: number): void;
export function __wbg_empty_free(a: number): void;
export function __wbg_get_empty_action_type(a: number): number;
export function __wbg_undoredo_free(a: number): void;
export function __wbg_get_undoredo_action_type(a: number): number;
export function __wbg_set_undoredo_action_type(a: number, b: number): void;
export function __wbg_boardsize_free(a: number): void;
export function __wbg_get_boardsize_height(a: number): number;
export function __wbg_set_boardsize_height(a: number, b: number): void;
export function __wbg_get_boardsize_width(a: number): number;
export function __wbg_set_boardsize_width(a: number, b: number): void;
export function __wbg_modify_free(a: number): void;
export function __wbg_get_modify_current(a: number, b: number): void;
export function __wbg_set_modify_current(a: number, b: number, c: number): void;
export function __wbg_get_modify_initial(a: number, b: number): void;
export function __wbg_set_modify_initial(a: number, b: number, c: number): void;
export function __wbg_remove_free(a: number): void;
export function __wbg_add_free(a: number): void;
export function __wbg_get_add_id(a: number, b: number): void;
export function __wbg_set_add_id(a: number, b: number, c: number): void;
export function __wbg_get_add_edit_type(a: number, b: number): void;
export function __wbg_set_add_edit_type(a: number, b: number, c: number): void;
export function __wbg_get_add_shape(a: number): number;
export function __wbg_set_add_shape(a: number, b: number): void;
export function __wbg_shape_free(a: number): void;
export function __wbg_get_shape_x(a: number): number;
export function __wbg_set_shape_x(a: number, b: number): void;
export function __wbg_get_shape_y(a: number): number;
export function __wbg_set_shape_y(a: number, b: number): void;
export function __wbg_get_shape_tool(a: number): number;
export function __wbg_set_shape_tool(a: number, b: number): void;
export function __wbg_get_shape_shape_type(a: number): number;
export function __wbg_set_shape_shape_type(a: number, b: number): void;
export function __wbg_get_shape_line_size(a: number): number;
export function __wbg_set_shape_line_size(a: number, b: number): void;
export function __wbg_get_shape_height(a: number): number;
export function __wbg_set_shape_height(a: number, b: number): void;
export function __wbg_get_shape_width(a: number): number;
export function __wbg_set_shape_width(a: number, b: number): void;
export function __wbg_get_shape_radius_x(a: number): number;
export function __wbg_set_shape_radius_x(a: number, b: number): void;
export function __wbg_get_shape_radius_y(a: number): number;
export function __wbg_set_shape_radius_y(a: number, b: number): void;
export function __wbg_get_shape_rotation(a: number): number;
export function __wbg_set_shape_rotation(a: number, b: number): void;
export function __wbg_get_shape_scale_x(a: number): number;
export function __wbg_set_shape_scale_x(a: number, b: number): void;
export function __wbg_get_shape_scale_y(a: number): number;
export function __wbg_set_shape_scale_y(a: number, b: number): void;
export function __wbg_get_shape_skew_x(a: number): number;
export function __wbg_set_shape_skew_x(a: number, b: number): void;
export function __wbg_get_shape_skew_y(a: number): number;
export function __wbg_set_shape_skew_y(a: number, b: number): void;
export function __wbg_get_shape_points(a: number, b: number): void;
export function __wbg_set_shape_points(a: number, b: number, c: number): void;
export function __wbg_get_shape_connected(a: number, b: number): void;
export function __wbg_set_shape_connected(a: number, b: number, c: number): void;
export function __wbg_get_shape_url(a: number, b: number): void;
export function __wbg_set_shape_url(a: number, b: number, c: number): void;
export function __wbg_get_emptydata_action_type(a: number): number;
export function __wbg_get_undoredodata_action_type(a: number): number;
export function __wbg_set_remove_shapes(a: number, b: number, c: number): void;
export function __wbg_set_emptydata_action_type(a: number, b: number): void;
export function __wbg_set_undoredodata_action_type(a: number, b: number): void;
export function __wbg_set_empty_action_type(a: number, b: number): void;
export function __wbg_set_titledata_title(a: number, b: number, c: number): void;
export function __wbg_set_undoredodata_action_id(a: number, b: number, c: number): void;
export function __wbg_set_info_status(a: number, b: number, c: number): void;
export function __wbg_set_undoredo_action_id(a: number, b: number, c: number): void;
export function __wbg_set_settitle_title(a: number, b: number, c: number): void;
export function __wbg_set_modify_id(a: number, b: number, c: number): void;
export function __wbg_set_modify_edit_type(a: number, b: number, c: number): void;
export function __wbg_set_remove_id(a: number, b: number, c: number): void;
export function __wbg_set_remove_edit_type(a: number, b: number, c: number): void;
export function __wbg_set_auth_token(a: number, b: number, c: number): void;
export function __wbg_set_info_action(a: number, b: number, c: number): void;
export function __wbg_set_shape_shape_id(a: number, b: number, c: number): void;
export function __wbg_set_shape_color(a: number, b: number, c: number): void;
export function __wbg_set_shape_line_type(a: number, b: number, c: number): void;
export function __wbg_set_sizedata_data(a: number, b: number): void;
export function __wbg_get_titledata_title(a: number, b: number): void;
export function __wbg_get_undoredodata_action_id(a: number, b: number): void;
export function __wbg_get_info_status(a: number, b: number): void;
export function __wbg_get_undoredo_action_id(a: number, b: number): void;
export function __wbg_get_settitle_title(a: number, b: number): void;
export function __wbg_get_modify_id(a: number, b: number): void;
export function __wbg_get_modify_edit_type(a: number, b: number): void;
export function __wbg_get_remove_id(a: number, b: number): void;
export function __wbg_get_remove_edit_type(a: number, b: number): void;
export function __wbg_get_auth_token(a: number, b: number): void;
export function __wbg_get_info_action(a: number, b: number): void;
export function __wbg_get_shape_shape_id(a: number, b: number): void;
export function __wbg_get_shape_color(a: number, b: number): void;
export function __wbg_get_shape_line_type(a: number, b: number): void;
export function __wbg_get_sizedata_data(a: number): number;
export function __wbg_get_remove_shapes(a: number, b: number): void;
export function __wbg_emptydata_free(a: number): void;
export function __wbg_quitdata_free(a: number): void;
export function __wbg_titledata_free(a: number): void;
export function __wbg_sizedata_free(a: number): void;
export function __wbg_undoredodata_free(a: number): void;
export function __wbg_settitle_free(a: number): void;
export function start(): void;
export function encode_server_msg(a: number, b: number): void;
export function decode_server_msg(a: number, b: number, c: number): void;
export function encode_user_msg(a: number, b: number): void;
export function decode_user_msg(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
