[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full", "time", "net"] }
tokio-stream = "0.1"
warp = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"]}
jwt-simple = "0.11"
data-encoding = "2.4"
weak-table = "0.3"
tokio-postgres = { version = "0.7.10", features = ["runtime", "with-serde_json-1"] }
argon2 = "0.5.2"
