[package]
name = "server"
version = "1.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full", "time", "net"] }
tokio-stream = "0.1"
warp = { version = "0.3", features = ["tls"] } 
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
uuid = { version = "1", features = ["v4", "fast-rng", "macro-diagnostics"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"]}
jwt-simple = "0.11"
data-encoding = "2.4"
weak-table = "0.3"
tokio-postgres = { version = "0.7.10", features = ["runtime", "with-serde_json-1", "array-impls"] }
argon2 = "0.5.2"
fast_log = { version = "1.6", features = ["lz4"]}
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
